-- V1: Patients tablosunun ilk kurulumu

CREATE TABLE IF NOT EXISTS patients (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                        tc_no VARCHAR(11) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    phone_number VARCHAR(15),
    gender VARCHAR(10),
    created_at DATE,

    CONSTRAINT pk_patients PRIMARY KEY (id),
    CONSTRAINT uk_patients_tc_no UNIQUE (tc_no)
    );