version: '3.8'

services:
  # --- 1. ALTYAPI SERVİSLERİ ---
  postgres:
    image: postgres:15
    container_name: hbbys-postgres
    environment:
      POSTGRES_USER: hbbys_user
      POSTGRES_PASSWORD: hbbys_password
      POSTGRES_DB: hbbys_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hbbys-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hbbys-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - hbbys-network

  redis:
    image: redis:7
    container_name: hbbys-redis
    ports:
      - "6379:6379"
    networks:
      - hbbys-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: hbbys-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/hbbys_db
      KC_DB_USERNAME: hbbys_user
      KC_DB_PASSWORD: hbbys_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - hbbys-network

  # --- 2. MİKROSERVİSLER ---

  eureka-server:
    build: ./discovery-server
    container_name: hbbys-eureka
    ports:
      - "8761:8761"
    networks:
      - hbbys-network

  api-gateway:
    build: ./api-gateway
    container_name: hbbys-gateway
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - keycloak
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/realms/hbys-realm
    networks:
      - hbbys-network

  patient-service:
    build: ./patient-service
    container_name: hbbys-patient
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/patient_db
      - SPRING_DATASOURCE_USERNAME=hbbys_user
      - SPRING_DATASOURCE_PASSWORD=hbbys_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/realms/hbys-realm
    networks:
      - hbbys-network

  doctor-service:
    build: ./doctor-service
    container_name: hbbys-doctor
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - redis
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hbbys_db
      - SPRING_DATASOURCE_USERNAME=hbbys_user
      - SPRING_DATASOURCE_PASSWORD=hbbys_password
      - SPRING_DATA_REDIS_HOST=redis
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/realms/hbys-realm
    networks:
      - hbbys-network

  appointment-service:
    build: ./appointment-service
    container_name: hbbys-appointment
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/appointment_db
      - SPRING_DATASOURCE_USERNAME=hbbys_user
      - SPRING_DATASOURCE_PASSWORD=hbbys_password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/realms/hbys-realm
    networks:
      - hbbys-network

  notification-service:
    build: ./notification-service
    container_name: hbbys-notification
    depends_on:
      - rabbitmq
      - eureka-server
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - hbbys-network

networks:
  hbbys-network:
    driver: bridge

volumes:
  postgres-data: