server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 1. HASTA SERVİSİ
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**

        # 2. DOKTOR SERVİSİ (YENİ EKLENDİ)
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**

        # 3. RANDEVU SERVİSİ (YENİ EKLENDİ)
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hbys-realm

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/