server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**

        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**

springdoc:
  swagger-ui:
    urls:
      - name: 1- Randevu Servisi
        url: /api/appointments/v3/api-docs
      - name: 2- Doktor Servisi
        url: /api/doctors/v3/api-docs
      - name: 3- Hasta Servisi
        url: /api/patients/v3/api-docs

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
