server:
  port: 8084
  forward-headers-strategy: framework  # BÜYÜK KURTARICI: Gateway'den gelen IP/Port bilgilerini kabul etmesini sağlar

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:postgresql://localhost:5433/hbbys_db
    username: hbbys_user
    password: hbbys_password
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 30       # Randevu servisinden gelen yoğun doğrulamalar için
      minimum-idle: 10
      connection-timeout: 20000

  # FLYWAY AYARLARI BURAYA EKLENDİ
  flyway:
    enabled: true
    baseline-on-migrate: true # Mevcut bir veritabanımız olduğu için bu ayar çok kritik

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hbys-realm

springdoc:
  api-docs:
    path: /api/doctors/v3/api-docs

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/