server:
  port: 8084

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:postgresql://localhost:5433/hbbys_db
    username: hbbys_user
    password: hbbys_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hbys-realm

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/