server:
  port: 8083 # Gateway 8082 idi, Patient Service 8083 olsun.

spring:
  application:
    name: patient-service

  # Veri Tabanı (PostgreSQL) Bağlantısı
  datasource:
    url: jdbc:postgresql://localhost:5432/hbbys_db
    username: hbbys_user
    password: hbbys_password
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Ayarları
  jpa:
    hibernate:
      ddl-auto: update # Biz Entity (sınıf) yazdığımızda, veri tabanında tabloyu otomatik oluşturur.
    show-sql: true # Geliştirme aşamasında konsolda SQL sorgularını görmek iyi olur.
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Güvenlik (Keycloak)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hbys-realm

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/