server:
  port: 8085

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://localhost:5433/appointment_db
    username: hbbys_user
    password: hbbys_password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis
      redis:
        # Önbellekteki veriler varsayılan olarak 10 dakika kalsın (milisaniye cinsinden)
        time-to-live: 600000
        cache-null-values: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hbys-realm

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/